# Python CircleCI 2.0 configuration file
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7

    working_directory: ~/repo

    steps:
      # Step 1: obtain repo from GitHub
      - checkout

      # Step 2: create virtual env and install dependencies
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            python3 -m pip install -r package/requirements.txt
            
      # Step 3: install package
      - run:
          name: install NAMDAnalyzer
          command: |
            . venv/bin/activate
            cd package
            python3 setup.py install

      # Step 4: run linter and tests
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            flake8 package/NAMDAnalyzer --config=package/.flake8 --statistics
            pytest package/tests -v --cov=NAMDAnalyzer

      # Step 5: run codecov
      - run:
          name: run codecov
          command: |
            . venv/bin/activate
            bash <(curl -s https://codecov.io/bash)
